version: "3.9"

services:
  mongo:
    image: mongo
    container_name: scd-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: tahasalam/scd-backend:v1
    container_name: scd-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nodevault
      - PORT=3000

volumes:
  mongo-data:
